version: "3.8"
services:
  backend:
    image: "sandreea/springboot-react-fullstack:22.1.2022.16.40.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev