version: "3.8"
services:
  backend:
    image: "sandreea/springboot-react-fullstack:10.1.2022.21.8.12"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev